added missing config files

diff --git a/docker/provision/ace/install b/docker/provision/ace/install
--- a/docker/provision/ace/install
+++ b/docker/provision/ace/install
@@ -74,3 +74,11 @@ if [ ! -e etc/local_networks.csv ]; then echo 'Indicator,Indicator_Type' > etc/l
 #activate-global-python-argcomplete
 ln -s /opt/signatures /opt/ace/etc/yara
 cp etc/saq.docker.ini etc/saq.ini
+
+for l in api apache
+do
+	if [ ! -e etc/$l\_logging.ini ]
+	then
+		cp -a etc/$l\_logging.example.ini etc/$l\_logging.ini || fail "unable to copy logging config for $l"
+	fi
+done
